### ISSUE TITLE
check.ActiveCalendarEvent not working?

### ISSUE THREAD

**Issue by n0ix** [languitar/autosuspend#35]
Hi,

first of all - really nice project :-)

Don't know if it is really a issue or just my fault but i can't get the ActiveCalendarEvent Check runnning.

I am getting the following errror:
```
Traceback (most recent call last):
  File "/usr/local/bin/autosuspend", line 11, in <module>
    load_entry_point('autosuspend==2.0.0.dev0', 'console_scripts', 'autosuspend')()
  File "/usr/local/lib/python3.5/dist-packages/autosuspend-2.0.0.dev0-py3.5.egg/autosuspend/__init__.py", line 515, in main
    error_none=True)
  File "/usr/local/lib/python3.5/dist-packages/autosuspend-2.0.0.dev0-py3.5.egg/autosuspend/__init__.py", line 382, in set_up_checks
    check = klass.create(name, config[section])
  File "/usr/local/lib/python3.5/dist-packages/autosuspend-2.0.0.dev0-py3.5.egg/autosuspend/checks/util.py", line 42, in create
    return cls(name, **cls.collect_init_args(config))  # type: ignore
TypeError: __init__() got an unexpected keyword argument 'password'
```

My autosuspend.conf:

```
[general]
interval = 60
idle_time = 900
suspend_cmd = /bin/systemctl suspend
wakeup_cmd = echo {timestamp:.0f} > /sys/class/rtc/rtc0/wakealarm
woke_up_file = /var/run/autosuspend-just-woke-up
min_sleep_time = 1200

[check.Ping]
enabled = true
hosts = 192.168.0.69

[check.RemoteUsers]
class = Users
enabled = true
name = myuser
terminal = .*
host = .*

[check.LocalUsers]
class = Users
enabled = false
name = .*
terminal = .*
host = localhost

[check.Smb]
enabled = true

[check.Nfs]
enabled = false

[check.Processes]
enabled = true
processes = rsync,btrbk

[check.Mpd]
enabled = false
timeout = 2

[check.Kodi]
enabled = false
timeout = 2

[check.ActiveConnection]
enabled = true
ports = 22

[check.Load]
enabled = false
threshold = 2.5

[check.NetworkBandwidth]
enabled = true
interfaces=enp3s0
threshold_send = 30000
threshold_receive = 30000

[check.ActiveCalendarEvent]
enabled = true
url = https://raw.githubusercontent.com/languitar/autosuspend/master/tests/test_data/single-change.ics

[wakeup.Command]
enabled = true
command = bash -c /etc/autosuspend/wakeup_time.sh
```
I am using Debian 9 as OS. Just ask if u need more information.

Thanks in advance

**Comment by languitar** [comment]
Sorry, this was simply a bug ;-) should be fixed now.
