### ISSUE TITLE
Be more robust in the presence of exceptions thrown by checks

### ISSUE THREAD

**Issue by Flowdalic** [languitar/autosuspend#356]
Recently, autosuspend terminated with

```
autosuspend[722]: 2023-04-20 00:17:13,118 - autosuspend.Processor - INFO - Starting new check iteration
autosuspend[722]: Traceback (most recent call last):
autosuspend[722]:   File "/usr/bin/autosuspend", line 11, in <module>
autosuspend[722]:     load_entry_point('autosuspend==3.0.0', 'console_scripts', 'autosuspend')()
autosuspend[722]:   File "/usr/lib/python3/dist-packages/autosuspend/__init__.py", line 751, in main
autosuspend[722]:     args.func(args, config)
autosuspend[722]:   File "/usr/lib/python3/dist-packages/autosuspend/__init__.py", line 733, in main_daemon
autosuspend[722]:     loop(
autosuspend[722]:   File "/usr/lib/python3/dist-packages/autosuspend/__init__.py", line 355, in loop
autosuspend[722]:     processor.iteration(
autosuspend[722]:   File "/usr/lib/python3/dist-packages/autosuspend/__init__.py", line 251, in iteration
autosuspend[722]:     active = execute_checks(self._activities, self._all_activities, self._logger)
autosuspend[722]:   File "/usr/lib/python3/dist-packages/autosuspend/__init__.py", line 142, in execute_checks
autosuspend[722]:     result = check.check()
autosuspend[722]:   File "/usr/lib/python3/dist-packages/autosuspend/checks/activity.py", line 77, in check
autosuspend[722]:     for c in psutil.net_connections()
autosuspend[722]:   File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 2153, in net_connections
autosuspend[722]:     return _psplatform.net_connections(kind)
autosuspend[722]:   File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1027, in net_connections
autosuspend[722]:     return _connections.retrieve(kind)
autosuspend[722]:   File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1001, in retrieve
autosuspend[722]:     inodes = self.get_all_inodes()
autosuspend[722]:   File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 849, in get_all_inodes
autosuspend[722]:     inodes.update(self.get_proc_inodes(pid))
autosuspend[722]:   File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 827, in get_proc_inodes
autosuspend[722]:     inode = readlink("%s/%s/fd/%s" % (self._procfs_path, pid, fd))
autosuspend[722]:   File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 211, in readlink
autosuspend[722]:     path = os.readlink(path)
autosuspend[722]: OSError: [Errno 36] File name too long: '/proc/2712298/fd/4'
systemd[1]: autosuspend.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: autosuspend.service: Failed with result 'exit-code'.
systemd[1]: autosuspend.service: Consumed 53min 41.672s CPU time.
```

In such situations you have basically two sensible design options:
1. Add a try/catch around the place where an individual check is invoked and catch (more-or-less) all exceptions and print an error message in that  case
2. Adjust the systemd.service to restart autosuspend

I would probably go with 1. But in any case, autosuspend should continue running in the presence of transient error conditions like the ENAMETOLONG for a `/proc` entry.

**Comment by languitar** [comment]
Usually there's exception handling in place for checks but I have never seen that exception. So that one lacks a check. Is that a known upstream issue in psutil? Look weird that requesting open network connections can actually raise this exception.

**Comment by Flowdalic** [comment]
> Is that a known upstream issue in psutil?

It asked myself the same question. But since we do not know the cause, this can't be answered. It would be great if we would know that symlink target of `/proc/2712298/fd/4` when this happened. I could even imagine that they used `ENAMETOLONG` in the kernel other cases (namespaces?) too.

That said, I could imagine that this could be viewed as something that is not a bug in psutil. In any case, autosuspend should be more robust by catching exceptions of checks.

**Comment by languitar** [comment]
What you are hitting here seems to be this bug: https://github.com/giampaolo/psutil/issues/1940. This should be fixed approx. >= psutil 5.8.0. Which version are you using?

**Comment by languitar** [comment]
Closing this for now due to the lack of feedback. Please reopen if this is still valid.
