### ISSUE TITLE
potalocker issue

### ISSUE THREAD

**Issue by bibitocarlos** [languitar/autosuspend#368]
Hi,
I needed to fix the compil issue because of this one, any idea ^^?

```
==> Les sources sont prêtes.
chargement des paquets…
avertissement : python-portalocker-2.7.0-1 est à jour -- réinstallation
résolution des dépendances…
recherche des conflits entre paquets…
Paquets (1) python-portalocker-2.7.0-1
Taille totale installée :      0,09 MiB
Taille de mise à jour nette :  0,00 MiB
:: Procéder à l’installation ? [O/n] o
```

```
autosuspend.service: Failed with result 'exit-code'.
mai 07 10:50:21 bibiserveur systemd[1]: autosuspend.service: Main process exited, code=exited, status=1/FAILURE
mai 07 10:50:21 bibiserveur autosuspend[865037]: ModuleNotFoundError: No module named 'portalocker'
mai 07 10:50:21 bibiserveur autosuspend[865037]:     import portalocker
mai 07 10:50:21 bibiserveur autosuspend[865037]:   File "/usr/lib/python3.11/site-packages/autosuspend/__init__.py", line 16, in <module>
mai 07 10:50:21 bibiserveur autosuspend[865037]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
mai 07 10:50:21 bibiserveur autosuspend[865037]:   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
mai 07 10:50:21 bibiserveur autosuspend[865037]:   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
mai 07 10:50:21 bibiserveur autosuspend[865037]:   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
mai 07 10:50:21 bibiserveur autosuspend[865037]:   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
mai 07 10:50:21 bibiserveur autosuspend[865037]:   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
mai 07 10:50:21 bibiserveur autosuspend[865037]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mai 07 10:50:21 bibiserveur autosuspend[865037]:     return _bootstrap._gcd_import(name[level:], package, level)
mai 07 10:50:21 bibiserveur autosuspend[865037]:   File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
mai 07 10:50:21 bibiserveur autosuspend[865037]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mai 07 10:50:21 bibiserveur autosuspend[865037]:     module = import_module(match.group('module'))
mai 07 10:50:21 bibiserveur autosuspend[865037]:   File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
mai 07 10:50:21 bibiserveur autosuspend[865037]:            ^^^^^^^^^^^^^^^^^^^^
mai 07 10:50:21 bibiserveur autosuspend[865037]:     return next(matches).load()
mai 07 10:50:21 bibiserveur autosuspend[865037]:   File "/usr/bin/autosuspend", line 25, in importlib_load_entry_point
mai 07 10:50:21 bibiserveur autosuspend[865037]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mai 07 10:50:21 bibiserveur autosuspend[865037]:     sys.exit(load_entry_point('autosuspend==4.3.0', 'console_scripts', 'autosuspend')())
mai 07 10:50:21 bibiserveur autosuspend[865037]:   File "/usr/bin/autosuspend", line 33, in <module>
mai 07 10:50:21 bibiserveur autosuspend[865037]: Traceback (most recent call last):
mai 07 10:50:21 bibiserveur systemd[1]: Started A daemon to suspend your server in case of inactivity.
```

**Comment by languitar** [comment]
This is most likely again solely related to Archlinux. Portalocker is an AUR package, which probably needs to be rebuilt and installed after the bump of Python to version 3.11.

**Comment by bibitocarlos** [comment]
Thanks !
