### ISSUE TITLE
Stopped working after upgrade on Archlinux

### ISSUE THREAD

**Issue by Mavyre** [languitar/autosuspend#380]
Autosuspend doesn't work anymore after Archlinux upgrade. The service throws a `StopIteration` error:

```
Traceback (most recent call last):
  File "/usr/bin/autosuspend", line 33, in <module>
    sys.exit(load_entry_point('autosuspend==4.3.2', 'console_scripts', 'autosuspend')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/autosuspend", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^
StopIteration
```

**Comment by languitar** [comment]
I can't reproduce this on my system. Did you rebuild the AUR package to be sure?

**Comment by Mavyre** [comment]
I'm sorry I didn't had any notification earlier. It seems that the latest pip python package was using a really old version (0.x.y, can't really remember) of autosuspend, which didn't work with the autoload as it was searching for the version 4.3.2. I had to manually install it from git using pip, and restart the service. Works now, but it seemed a bit odd

**Comment by languitar** [comment]
There is an up to date AUR package. You should use that one to avoid such issues.
