### ISSUE TITLE
Autosuspend fails to launch

### ISSUE THREAD

**Issue by nekthar** [languitar/autosuspend#40]
Hi,

When selecting checks other than "Ping", I receive the following error in journalctl.

Jun 24 08:43:28 Server-PC autosuspend[1936]: Traceback (most recent call last):
Jun 24 08:43:28 Server-PC autosuspend[1936]:   File "/usr/local/bin/autosuspend", line 11, in <module>
Jun 24 08:43:28 Server-PC autosuspend[1936]:     load_entry_point('autosuspend==2.0.0.dev0', 'console_scripts', 'autosuspend')()
Jun 24 08:43:28 Server-PC autosuspend[1936]:   File "/usr/local/lib/python3.5/dist-packages/autosuspend-2.0.0.dev0-py3.5.egg/autosuspend/__init__.py", line 516, in main
Jun 24 08:43:28 Server-PC autosuspend[1936]:     error_none=True)
Jun 24 08:43:28 Server-PC autosuspend[1936]:   File "/usr/local/lib/python3.5/dist-packages/autosuspend-2.0.0.dev0-py3.5.egg/autosuspend/__init__.py", line 392, in set_up_checks
Jun 24 08:43:28 Server-PC autosuspend[1936]:     raise ConfigurationError('No checks enabled')
Jun 24 08:43:28 Server-PC autosuspend[1936]: autosuspend.checks.ConfigurationError: No checks enabled
Jun 24 08:43:28 Server-PC systemd[1]: autosuspend.service: Main process exited, code=exited, status=1/FAILURE
Jun 24 08:43:28 Server-PC systemd[1]: autosuspend.service: Unit entered failed state.
Jun 24 08:43:28 Server-PC systemd[1]: autosuspend.service: Failed with result 'exit-code'.

Autosuspend subsequently fails to start.

Edit: autosuspend.conf
[general]
interval = 30
idle_time = 900
suspend_cmd = /usr/bin/systemctl suspend
wakeup_cmd = echo {timestamp:.0f} > /sys/class/rtc/rtc0/wakealarm
wakeup_delta = 30
notify_cmd_wakeup = su myuser -c notify-send -a autosuspend 'Suspending the system. Wake up at {iso}'
notify_cmd_no_wakeup = su myuser -c notify-send -a autosuspend 'Suspending the system.'

[check.NetworkBandwidth]
interfaces = enp2s0
threshold_send = 250000
threshold_recieve = 250000

[check.Ping]
enabled = true
hosts = 192.168.0.10

[check.Kodi]
enabled = true
url = http://localhost:8080/jsonrpc

[check.Load]
threshold = 2.5

**Comment by nekthar** [comment]
Apologies, I had failed to enter "enabled = true" for all options.
