### ISSUE TITLE
MPD connection issues

### ISSUE THREAD

**Issue by languitar** [languitar/autosuspend#46]
This is split out of #45 from @indianahorst

```
Sep 7 10:33:03 localhost autosuspend[22676]: 2018-09-07 10:33:03,248 - loop - DEBUG - Executing check Mpd
Sep 7 10:33:03 localhost autosuspend[22676]: 2018-09-07 10:33:03,251 - mpd.base - INFO - Calling MPD connect('localhost', 6600, timeout=None)
Sep 7 10:33:03 localhost autosuspend[22676]: 2018-09-07 10:33:03,260 - loop - WARNING - Check Mpd[class=Mpd] failed. Ignoring...
Sep 7 10:33:03 localhost autosuspend[22676]: Traceback (most recent call last):
Sep 7 10:33:03 localhost autosuspend[22676]: File "/usr/bin/autosuspend", line 168, in check
Sep 7 10:33:03 localhost autosuspend[22676]: state = self._get_state()
Sep 7 10:33:03 localhost autosuspend[22676]: File "/usr/bin/autosuspend", line 160, in _get_state
Sep 7 10:33:03 localhost autosuspend[22676]: client.connect(self._host, self._port)
Sep 7 10:33:03 localhost autosuspend[22676]: File "/usr/lib/python3/dist-packages/mpd/base.py", line 641, in connect
Sep 7 10:33:03 localhost autosuspend[22676]: self._sock = self._connect_tcp(host, port)
Sep 7 10:33:03 localhost autosuspend[22676]: File "/usr/lib/python3/dist-packages/mpd/base.py", line 604, in _connect_tcp
Sep 7 10:33:03 localhost autosuspend[22676]: raise err
Sep 7 10:33:03 localhost autosuspend[22676]: File "/usr/lib/python3/dist-packages/mpd/base.py", line 597, in _connect_tcp
Sep 7 10:33:03 localhost autosuspend[22676]: sock.connect(sa)
Sep 7 10:33:03 localhost autosuspend[22676]: ConnectionRefusedError: [Errno 111] Connection refused
Sep 7 10:33:03 localhost autosuspend[22676]: During handling of the above exception, another exception occurred:
Sep 7 10:33:03 localhost autosuspend[22676]: Traceback (most recent call last):
Sep 7 10:33:03 localhost autosuspend[22676]: File "/usr/bin/autosuspend", line 559, in execute_checks
Sep 7 10:33:03 localhost autosuspend[22676]: result = check.check()
Sep 7 10:33:03 localhost autosuspend[22676]: File "/usr/bin/autosuspend", line 177, in check
Sep 7 10:33:03 localhost autosuspend[22676]: raise TemporaryCheckError(error)
Sep 7 10:33:03 localhost autosuspend[22676]: TemporaryCheckError: [Errno 111] Connection refused
```

**Comment by languitar** [comment]
@indianahorst could you please execute the following command and paste the result (if any) on the affected system:

```
python3 -c "from mpd import MPDClient; c = MPDClient(); c.connect('localhost', 6600)"
```

**Comment by indianahorst** [comment]
@languitar 
When I execute the command above, I get no output (not even an empty line).

**Comment by indianahorst** [comment]
Okay, I've found the problem. Yesterday I had inserted the line 

`bind_to_address		"127.0.0.1"`

in .mpdconf. If this line is present and MPD is also bound to 127.0.0.1, then I get the empty output of the command above. 

But if the line `bind_to_address		"127.0.0.1"` is commented out, I get the following error with your command line above:


```
$ python3 -c "from mpd import MPDClient; c = MPDClient(); c.connect('localhost', 6600)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/mpd/base.py", line 641, in connect
    self._sock = self._connect_tcp(host, port)
  File "/usr/lib/python3/dist-packages/mpd/base.py", line 604, in _connect_tcp
    raise err
  File "/usr/lib/python3/dist-packages/mpd/base.py", line 597, in _connect_tcp
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

If I understand it correctly, autosuspend assumes that MPD is listening on 127.0.0.1. But this is not  necessarily true, so autosuspend should check also the real IP address of the system, not only localhost/127.0.0.1.

**Comment by languitar** [comment]
No, autosuspend does what ever you configure it to and what ever your DNS system resolves hostnames to. With `bind_to_address "192.168.1.8"` you configure your MPD to only listen on an external IP address and not on 127.0.0.1. But that is what the name `localhost` resolves to on usual systems. Thus, connection fails.

Is there any specific reason why you want to restrict MPD to only the external IP address? You could simply use 0.0.0.0 to make it listen to all addresses. Otherwise, you have to use 192.168.1.8 in the autosuspend configuration.
