### ISSUE TITLE
broadcast-logging

### ISSUE THREAD

**Issue by Dodgexander** [languitar/autosuspend#55]
first thanks for this daemon, its brilliant.

I have been using it on my home server and have been trying to set up remote logging as described in debugging section of the manual.

Following the steps from https://github.com/languitar/broadcast-logging and changing the logging handler to broadcasteHandler in my autosuspend-logging.conf isn't working and returns:

```
tim@themole:/usr/local/bin$ autosuspend -l autosuspend-logging.conf
WARNING:autosuspend:Unable to configure logging from file <_io.TextIOWrapper name='autosuspend-logging.conf' mode='r' encoding='UTF-8'>. Falling back to warning level.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/autosuspend-2.1.0.dev0-py3.6.egg/autosuspend/__init__.py", line 500, in configure_logging
    logging.config.fileConfig(file_or_flag)
  File "/usr/lib/python3.6/logging/config.py", line 84, in fileConfig
    handlers = _install_handlers(cp, formatters)
  File "/usr/lib/python3.6/logging/config.py", line 139, in _install_handlers
    section = cp["handler_%s" % hand]
  File "/usr/lib/python3.6/configparser.py", line 959, in __getitem__
    raise KeyError(key)
KeyError: 'handler_broadcasteHandler'
```

Is there anything I can do to get it to work, or an example conf I can use?

thanks again!

**Comment by languitar** [comment]
Looks like a typo: `handler_broadcasteHandler` has an additional `e` before `Handler`.
