### ISSUE TITLE
docs: kodi default url not used

### ISSUE THREAD

**Issue by nioncode** [languitar/autosuspend#58]
The documentation for `Kodi` and `KodiIdleTime` says that the default for `url` is `http://localhost:8080/jsonrpc`.
However, when not setting the `url` config option, `autosuspend` crashes with:
```
2019-08-04 17:01:32,950 - autosuspend - INFO - Configuring check Kodi with class Kodi from module autosuspend.checks.activity using config section items {'enabled': 'true'}
Traceback (most recent call last):
  File "/opt/lib/python3.7/site-packages/autosuspend-2.0.6-py3.7.egg/autosuspend/checks/util.py", line 30, in collect_init_args
    args['url'] = config['url']
  File "/configparser.py", line 1251, in __getitem__
KeyError: 'url'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/bin/autosuspend", line 11, in <module>
    load_entry_point('autosuspend==2.0.6', 'console_scripts', 'autosuspend')()
  File "/opt/lib/python3.7/site-packages/autosuspend-2.0.6-py3.7.egg/autosuspend/__init__.py", line 519, in main
    error_none=True)
  File "/opt/lib/python3.7/site-packages/autosuspend-2.0.6-py3.7.egg/autosuspend/__init__.py", line 385, in set_up_checks
    check = klass.create(name, config[section])
  File "/opt/lib/python3.7/site-packages/autosuspend-2.0.6-py3.7.egg/autosuspend/checks/util.py", line 45, in create
    return cls(name, **cls.collect_init_args(config))  # type: ignore
  File "/opt/lib/python3.7/site-packages/autosuspend-2.0.6-py3.7.egg/autosuspend/checks/util.py", line 41, in collect_init_args
    'Lacks ' + str(error) + ' config entry') from error
autosuspend.checks.ConfigurationError: Lacks 'url' config entry
```

**Comment by languitar** [comment]
Thanks for spotting this

**Comment by nioncode** [comment]
I fixed this, but the commit is based on #60 so I'm waiting for this to get merged first.

**Comment by languitar** [comment]
Any progress on the PR for this one?

**Comment by nioncode** [comment]
Sorry, totally forgot about it. Just pushed.
