### ISSUE TITLE
autosuspend  raise TemporaryCheckError(error) from error

### ISSUE THREAD

**Issue by estatistics** [languitar/autosuspend#597]
autosuspend version  (7.0.2-1) in trixie system (debian),

thousand of these messages

Nov 18 12:38:48 eros autosuspend[1405]:     raise TemporaryCheckError(error) from error
Nov 18 12:54:48 eros autosuspend[1405]:     raise HTTPError(http_error_msg, response=self)
Nov 18 12:54:48 eros autosuspend[1405]:     raise TemporaryCheckError(error) from error
Nov 18 13:10:48 eros autosuspend[1405]:     raise HTTPError(http_error_msg, response=self)
Nov 18 13:10:48 eros autosuspend[1405]:     raise TemporaryCheckError(error) from error
Nov 18 13:26:49 eros autosuspend[1405]:     raise HTTPError(http_error_msg, response=self)
Nov 18 13:26:49 eros autosuspend[1405]:     raise TemporaryCheckError(error) from error
Nov 18 13:42:49 eros autosuspend[1405]:     raise HTTPError(http_error_msg, response=self)
Nov 18 13:42:49 eros autosuspend[1405]:     raise TemporaryCheckError(error) from error
Nov 18 13:58:49 eros autosuspend[1405]:     raise HTTPError(http_error_msg, response=self)
Nov 18 13:58:49 eros autosuspend[1405]:     raise TemporaryCheckError(error) from error
Nov 18 14:14:50 eros autosuspend[1405]:     raise HTTPError(http_error_msg, response=self)
Nov 18 14:14:50 eros autosuspend[1405]:     raise TemporaryCheckError(error) from error
Nov 18 14:30:50 eros autosuspend[1405]:     raise HTTPError(http_error_msg, response=self)

**Comment by languitar** [comment]
Are you sure that autosuspend has started correctly? This messages look garbled.

**Comment by estatistics** [comment]
dont know. after some changes. now these messages are spawn in journalctl 

Dec 05 10:56:31 eros kernel: [UFW BLOCK] IN=enp3s0 OUT= MAC=01:00:5e:00:00:01:e0:b6:68:51:ce:cd:08:00 SRC=192.168.2.1 DST=224.0.0.1 LEN=32 TOS=0x18 PREC=0x40 TTL=1 ID=11575 DF PROTO=2                                                                                                                                               
Dec 05 10:56:39 eros autosuspend[1336]: 2024-12-05 10:56:39,072 - autosuspend.Processor - INFO - System is idle since 2024-12-05 16:47:09.042670+00:00
Dec 05 10:56:39 eros autosuspend[1336]: 2024-12-05 10:56:39,072 - autosuspend.Processor - INFO - Desired idle time of 900.0 s not reached yet. Currently idle since 560.028543 s
Dec 05 10:56:55 eros kernel: [UFW BLOCK] IN=enp3s0 OUT= MAC=01:00:5e:00:00:01:e0:b6:68:51:ce:cd:08:00 SRC=192.168.2.1 DST=224.0.0.1 LEN=32 TOS=0x18 PREC=0x40 TTL=1 ID=13081 DF PROTO=2                                                                                                                                               
Dec 05 10:57:09 eros autosuspend[1336]: 2024-12-05 10:57:09,073 - autosuspend.Processor - INFO - Starting new check iteration
Dec 05 10:57:19 eros autosuspend[1336]: 2024-12-05 10:57:19,074 - autosuspend.Processor - INFO - System is idle since 2024-12-05 16:47:09.042670+00:00
Dec 05 10:57:19 eros autosuspend[1336]: 2024-12-05 10:57:19,075 - autosuspend.Processor - INFO - Desired idle time of 900.0 s not reached yet. Currently idle since 600.030527 s
Dec 05 10:57:19 eros kernel: [UFW BLOCK] IN=enp3s0 OUT= MAC=01:00:5e:00:00:01:e0:b6:68:51:ce:cd:08:00 SRC=192.168.2.1 DST=224.0.0.1 LEN=32 TOS=0x18 PREC=0x40 TTL=1 ID=15053 DF PROTO=2                                                                                                                                               
Dec 05 10:57:31 eros kernel: [UFW BLOCK] IN=enp3s0 OUT= MAC=01:00:5e:00:00:01:e0:b6:68:51:ce:cd:08:00 SRC=192.168.2.1 DST=224.0.0.1 LEN=32 TOS=0x18 PREC=0x40 TTL=1 ID=15530 DF PROTO=2                                                                                                                                               
Dec 05 10:57:49 eros autosuspend[1336]: 2024-12-05 10:57:49,075 - autosuspend.Processor - INFO - Starting new check iteration
Dec 05 10:57:55 eros kernel: [UFW BLOCK] IN=enp3s0 OUT= MAC=01:00:5e:00:00:01:e0:b6:68:51:ce:cd:08:00 SRC=192.168.2.1 DST=224.0.0.1 LEN=32 TOS=0x18 PREC=0x40 TTL=1 ID=17070 DF PROTO=2                                                                                                                                               
Dec 05 10:57:59 eros autosuspend[1336]: 2024-12-05 10:57:59,076 - autosuspend.Processor - INFO - System is idle since 2024-12-05 16:47:09.042670+00:00
Dec 05 10:57:59 eros autosuspend[1336]: 2024-12-05 10:57:59,076 - autosuspend.Processor - INFO - Desired idle time of 900.0 s not reached yet. Currently idle since 640.032599 s
Dec 05 10:58:19 eros kernel: [UFW BLOCK] IN=enp3s0 OUT= MAC=01:00:5e:00:00:01:e0:b6:68:51:ce:cd:08:00 SRC=192.168.2.1 DST=224.0.0.1 LEN=32 TOS=0x18 PREC=0x40 TTL=1 ID=18023 DF PROTO=2                                                                                                                                               
Dec 05 10:58:29 eros autosuspend[1336]: 2024-12-05 10:58:29,077 - autosuspend.Processor - INFO - Starting new check iteration
Dec 05 10:58:31 eros kernel: [UFW BLOCK] IN=enp3s0 OUT= MAC=01:00:5e:00:00:01:e0:b6:68:51:ce:cd:08:00 SRC=192.168.2.1 DST=224.0.0.1 LEN=32 TOS=0x18 PREC=0x40 TTL=1 ID=18425 DF PROTO=2                                                                                                                                               
Dec 05 10:58:39 eros autosuspend[1336]: 2024-12-05 10:58:39,078 - autosuspend.Processor - INFO - System is idle since 2024-12-05 16:47:09.042670+00:00
Dec 05 10:58:39 eros autosuspend[1336]: 2024-12-05 10:58:39,078 - autosuspend.Processor

**Comment by languitar** [comment]
Sorry, missed your reply. Most of the logs you posted are unrelated to autosuspend.

**Comment by languitar** [comment]
Without further infos, I can't help much here.

**Comment by estatistics** [comment]
this may help? .... in 1 month, 166212 entries in my journalctl
```
Dec 25 14:12:04 eros autosuspend[1394]: 2024-12-25 14:12:04,267 - autosuspend.Processor - INFO - System is idle since 2024-12-25 20:09:54.259746+00:00
Dec 25 14:11:54 eros autosuspend[1394]: 2024-12-25 14:11:54,266 - autosuspend.Processor - INFO - Starting new check iteration
Dec 25 14:11:24 eros autosuspend[1394]: 2024-12-25 14:11:24,265 - autosuspend.Processor - INFO - Desired idle time of 900.0 s not reached yet. Currently idle since 80.004279 s
Dec 25 14:11:24 eros autosuspend[1394]: 2024-12-25 14:11:24,265 - autosuspend.Processor - INFO - System is idle since 2024-12-25 20:09:54.259746+00:00
Dec 25 14:11:14 eros autosuspend[1394]: 2024-12-25 14:11:14,264 - autosuspend.Processor - INFO - Starting new check iteration
Dec 25 14:10:44 eros autosuspend[1394]: 2024-12-25 14:10:44,263 - autosuspend.Processor - INFO - Desired idle time of 900.0 s not reached yet. Currently idle since 40.002291 s
Dec 25 14:10:44 eros autosuspend[1394]: 2024-12-25 14:10:44,263 - autosuspend.Processor - INFO - System is idle since 2024-12-25 20:09:54.259746+00:00
Dec 25 14:10:34 eros autosuspend[1394]: 2024-12-25 14:10:34,262 - autosuspend.Processor - INFO - Starting new check iteration
Dec 25 14:10:04 eros autosuspend[1394]: 2024-12-25 14:10:04,261 - autosuspend.Processor - INFO - Desired idle time of 900.0 s not reached yet. Currently idle since 0.0 s
Dec 25 14:10:04 eros autosuspend[1394]: 2024-12-25 14:10:04,261 - autosuspend.Processor - INFO - System is idle since 2024-12-25 20:09:54.259746+00:00
Dec 25 14:09:54 eros autosuspend[1394]: 2024-12-25 14:09:54,259 - autosuspend.Processor - INFO - Starting new check iteration
Dec 25 14:09:24 eros autosuspend[1394]: subprocess.CalledProcessError: Command '/usr/bin/systemctl suspend' returned non-zero exit status 1.
Dec 25 14:09:24 eros autosuspend[1394]:     raise CalledProcessError(retcode, cmd)
Dec 25 14:09:24 eros autosuspend[1394]:   File "/usr/lib/python3.12/subprocess.py", line 413, in check_call
Dec 25 14:09:24 eros autosuspend[1394]:     subprocess.check_call(command, shell=True)
Dec 25 14:09:24 eros autosuspend[1394]:   File "/usr/lib/python3/dist-packages/autosuspend/__init__.py", line 46, in execute_suspend
Dec 25 14:09:24 eros autosuspend[1394]: Traceback (most recent call last):
Dec 25 14:09:24 eros autosuspend[1394]: 2024-12-25 14:09:24,259 - autosuspend - WARNING - Unable to execute suspend command: /usr/bin/systemctl suspend
Dec 25 14:09:24 eros autosuspend[1394]: 2024-12-25 14:09:24,253 - autosuspend - INFO - Suspending using command: /usr/bin/systemctl suspend with next wake up at None
Dec 25 14:09:24 eros autosuspend[1394]: 2024-12-25 14:09:24,253 - autosuspend - INFO - No suitable notification command configured.
Dec 25 14:09:24 eros autosuspend[1394]: 2024-12-25 14:09:24,253 - autosuspend.Processor - INFO - Going to suspend. Resetting state
Dec 25 14:09:24 eros autosuspend[1394]: autosuspend.checks.TemporaryCheckError: 404 Client Error: Not Found for url: http://example.org/test.ics
Dec 25 14:09:24 eros autosuspend[1394]:     raise TemporaryCheckError(error) from error
Dec 25 14:09:24 eros autosuspend[1394]:   File "/usr/lib/python3/dist-packages/autosuspend/checks/util.py", line 119, in request
Dec 25 14:09:24 eros autosuspend[1394]:                ^^^^^^^^^^^^^^
Dec 25 14:09:24 eros autosuspend[1394]:     response = self.request()
Dec 25 14:09:24 eros autosuspend[1394]:   File "/usr/lib/python3/dist-packages/autosuspend/checks/ical.py", line 324, in check
Dec 25 14:09:24 eros autosuspend[1394]:            ^^^^^^^^^^^^^^^^^^^^^^
Dec 25 14:09:24 eros autosuspend[1394]:     return check.check(timestamp)
Dec 25 14:09:24 eros autosuspend[1394]:   File "/usr/lib/python3/dist-packages/autosuspend/__init__.py", line 159, in _safe_execute_wakeup
Dec 25 14:09:24 eros autosuspend[1394]: Traceback (most recent call last):
Dec 25 14:09:24 eros autosuspend[1394]: The above exception was the direct cause of the following exception:
Dec 25 14:09:24 eros autosuspend[1394]: requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://example.org/test.ics
Dec 25 14:09:24 eros autosuspend[1394]:     raise HTTPError(http_error_msg, response=self)
Dec 25 14:09:24 eros autosuspend[1394]:   File "/usr/lib/python3/dist-packages/requests/models.py", line 1024, in raise_for_status
Dec 25 14:09:24 eros autosuspend[1394]:     reply.raise_for_status()
Dec 25 14:09:24 eros autosuspend[1394]:   File "/usr/lib/python3/dist-packages/autosuspend/checks/util.py", line 116, in request
Dec 25 14:09:24 eros autosuspend[1394]: Traceback (most recent call last):
Dec 25 14:09:24 eros autosuspend[1394]: 2024-12-25 14:09:24,252 - autosuspend.Processor - WARNING - Wakeup Calendar[class=Calendar] failed. Ignoring...
Dec 25 14:09:23 eros autosuspend[1394]: 2024-12-25 14:09:23,989 - autosuspend.Processor - INFO - System is idle long enough.
Dec 25 14:09:23 eros autosuspend[1394]: 2024-12-25 14:09:23,989 - autosuspend.Processor - INFO - System is idle since 2024-12-25 19:53:53.939622+00:00
Dec 25 14:09:13 eros autosuspend[1394]: 2024-12-25 14:09:13,987 - autosuspend.Processor - INFO - Starting new check iteration
Dec 25 14:08:43 eros autosuspend[1394]: 2024-12-25 14:08:43,987 - autosuspend.Processor - INFO - Desired idle time of 900.0 s not reached yet. Currently idle since 880.046127 s
Dec 25 14:08:43 eros autosuspend[1394]: 2024-12-25 14:08:43,987 - autosuspend.Processor - INFO - System is idle since 2024-12-25 19:53:53.939622+00:00
Dec 25 14:08:33 eros autosuspend[1394]: 2024-12-25 14:08:33,985 - autosuspend.Processor - INFO - Starting new check iteration
Dec 25 14:08:03 eros autosuspend[1394]: 2024-12-25 14:08:03,985 - autosuspend.Processor - INFO - Desired idle time of 900.0 s not reached yet. Currently idle since 840.044095 s
Dec 25 14:08:03 eros autosuspend[1394]: 2024-12-25 14:08:03,985 - autosuspend.Processor - INFO - System is idle since 2024-12-25 19:53:53.939622+00:00
Dec 25 14:07:53 eros autosuspend[1394]: 2024-12-25 14:07:53,983 - autosuspend.Processor - INFO - Starting new check iteration
Dec 25 14:07:23 eros autosuspend[1394]: 2024-12-25 14:07:23,983 - autosuspend.Processor - INFO - Desired idle time of 900.0 s not reached yet. Currently idle since 800.042015 s
Dec 25 14:07:23 eros autosuspend[1394]: 2024-12-25 14:07:23,983 - autosuspend.Processor - INFO - System is idle since 2024-12-25 19:53:53.939622+00:00
....
```


autosuspend --version
usage: autosuspend [-h] [-c FILE] [-l FILE | -d] {version,daemon,presuspend} ...
autosuspend: error: the following arguments are required: subcommand

 lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux trixie/sid
Release:        n/a
Codename:       trixie

-----------------------------------------------------------------
```
sudo systemctl status autosuspend
● autosuspend.service - A daemon to suspend your server in case of inactivity
     Loaded: loaded (/usr/lib/systemd/system/autosuspend.service; enabled; preset: enabled)
     Active: active (running) since Mon 2025-01-20 03:10:56 CST; 23min ago
 Invocation: da264198252f4462a572fffc67c4f9bc
       Docs: https://autosuspend.readthedocs.io/en/latest/systemd_integration.html
   Main PID: 1483 (autosuspend)
      Tasks: 1 (limit: 38179)
     Memory: 59.1M (peak: 60.4M)
        CPU: 299ms
     CGroup: /system.slice/autosuspend.service
             └─1483 /usr/bin/python3 /usr/bin/autosuspend -l /etc/autosuspend-logging.conf daemon

Jan 20 03:32:18 eros autosuspend[1483]: 2025-01-20 03:32:18,150 - autosuspend.Processor - INFO - Desired idle time of 900.0 s not reached yet. Currently idle since 320.016414 s
Jan 20 03:32:48 eros autosuspend[1483]: 2025-01-20 03:32:48,150 - autosuspend.Processor - INFO - Starting new check iteration
Jan 20 03:32:58 eros autosuspend[1483]: 2025-01-20 03:32:58,151 - autosuspend.Processor - INFO - System is idle since 2025-01-20 09:26:48.131779+00:00
Jan 20 03:32:58 eros autosuspend[1483]: 2025-01-20 03:32:58,152 - autosuspend.Processor - INFO - Desired idle time of 900.0 s not reached yet. Currently idle since 360.018517 s
Jan 20 03:33:28 eros autosuspend[1483]: 2025-01-20 03:33:28,152 - autosuspend.Processor - INFO - Starting new check iteration
Jan 20 03:33:38 eros autosuspend[1483]: 2025-01-20 03:33:38,154 - autosuspend.Processor - INFO - System is idle since 2025-01-20 09:26:48.131779+00:00
Jan 20 03:33:38 eros autosuspend[1483]: 2025-01-20 03:33:38,154 - autosuspend.Processor - INFO - Desired idle time of 900.0 s not reached yet. Currently idle since 400.020507 s
Jan 20 03:34:08 eros autosuspend[1483]: 2025-01-20 03:34:08,154 - autosuspend.Processor - INFO - Starting new check iteration
Jan 20 03:34:18 eros autosuspend[1483]: 2025-01-20 03:34:18,155 - autosuspend.Processor - INFO - System is idle since 2025-01-20 09:26:48.131779+00:00
Jan 20 03:34:18 eros autosuspend[1483]: 2025-01-20 03:34:18,156 - autosuspend.Processor - INFO - Desired idle time of 900.0 s not reached yet. Currently idle since 440.022542 s
```
