### ISSUE TITLE
v3.0: AttributeError: module 'autosuspend.checks.activity' has no attribute 'ActiveConnections'

### ISSUE THREAD

**Issue by malvinas2** [languitar/autosuspend#68]
Hello, 

I installed v3.0 from source using git and python3 setup.py install and receive the following error message when I try to start the program (Ubuntu 16.04 LTS): 

```
root@ubuntu:~/autosuspend# /usr/local/bin/autosuspend
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/autosuspend-3.0.0.dev0-py3.5.egg/autosuspend/__init__.py", line 386, in set_up_checks
    import_class)
AttributeError: module 'autosuspend.checks.activity' has no attribute 'ActiveConnections'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/autosuspend", line 9, in <module>
    load_entry_point('autosuspend==3.0.0.dev0', 'console_scripts', 'autosuspend')()
  File "/usr/local/lib/python3.5/dist-packages/autosuspend-3.0.0.dev0-py3.5.egg/autosuspend/__init__.py", line 553, in main
    error_none=True,
  File "/usr/local/lib/python3.5/dist-packages/autosuspend-3.0.0.dev0-py3.5.egg/autosuspend/__init__.py", line 390, in set_up_checks
    'Class does not exist'.format(class_name)) from error
autosuspend.checks.ConfigurationError: Cannot create built-in check named ActiveConnections: Class does not exist

```

**Comment by malvinas2** [comment]
Configuration error, "ActiveConnectionS" ....
