### ISSUE TITLE
systemd service died after some time and did not restart

### ISSUE THREAD

**Issue by weili-jiang** [languitar/autosuspend#82]
I left my machine running for a long while, and was surprised that it hadn't suspended. Looking at the logs I saw this:

```
May 07 16:40:48 autosuspend[12450]: 2020-05-07 16:40:48,974 - autosuspend.Processor - INFO - System is active. Resetting state
May 07 16:41:18 autosuspend[12450]: 2020-05-07 16:41:18,978 - autosuspend.Processor - INFO - Starting new check iteration
May 07 16:41:19 autosuspend[12450]: 2020-05-07 16:41:19,962 - dbus.proxies - ERROR - Introspect error on :1.5:/org/freedesktop/login1/session/_3458: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownObject: Unknown object '/org/free>
May 07 16:41:20 autosuspend[12450]: Traceback (most recent call last):
May 07 16:41:20 autosuspend[12450]:   File "/usr/bin/autosuspend", line 11, in <module>
May 07 16:41:20 autosuspend[12450]:     load_entry_point('autosuspend==3.0.0', 'console_scripts', 'autosuspend')()
May 07 16:41:20 autosuspend[12450]:   File "/usr/lib/python3/dist-packages/autosuspend/__init__.py", line 751, in main
May 07 16:41:20 autosuspend[12450]:     args.func(args, config)
May 07 16:41:20 autosuspend[12450]:   File "/usr/lib/python3/dist-packages/autosuspend/__init__.py", line 733, in main_daemon
May 07 16:41:20 autosuspend[12450]:     loop(
May 07 16:41:20 autosuspend[12450]:   File "/usr/lib/python3/dist-packages/autosuspend/__init__.py", line 355, in loop
May 07 16:41:20 autosuspend[12450]:     processor.iteration(
May 07 16:41:20 autosuspend[12450]:   File "/usr/lib/python3/dist-packages/autosuspend/__init__.py", line 251, in iteration
May 07 16:41:20 autosuspend[12450]:     active = execute_checks(self._activities, self._all_activities, self._logger)
May 07 16:41:20 autosuspend[12450]:   File "/usr/lib/python3/dist-packages/autosuspend/__init__.py", line 142, in execute_checks
May 07 16:41:20 autosuspend[12450]:     result = check.check()
May 07 16:41:20 autosuspend[12450]:   File "/usr/lib/python3/dist-packages/autosuspend/checks/activity.py", line 694, in check
May 07 16:41:20 autosuspend[12450]:     for session_id, properties in list_logind_sessions():
May 07 16:41:20 autosuspend[12450]:   File "/usr/lib/python3/dist-packages/autosuspend/util/systemd.py", line 35, in list_logind_sessions
May 07 16:41:20 autosuspend[12450]:     properties = properties_interface.GetAll("org.freedesktop.login1.Session")
May 07 16:41:20 autosuspend[12450]:   File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 72, in __call__
May 07 16:41:20 autosuspend[12450]:     return self._proxy_method(*args, **keywords)
May 07 16:41:20 autosuspend[12450]:   File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
May 07 16:41:20 autosuspend[12450]:     return self._connection.call_blocking(self._named_service,
May 07 16:41:20 autosuspend[12450]:   File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
May 07 16:41:20 autosuspend[12450]:     reply_message = self.send_message_with_reply_and_block(
May 07 16:41:20 autosuspend[12450]: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownObject: Unknown object '/org/freedesktop/login1/session/_3458'.
May 07 16:41:27 systemd[1]: autosuspend.service: Main process exited, code=exited, status=1/FAILURE
May 07 16:41:27 systemd[1]: autosuspend.service: Failed with result 'exit-code'.
```

---

Running `autosuspend` 3.0-1 from Ubuntu.

`/etc/os-release`:
```
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
`uname -a`:
```
Linux hpm 5.4.0-26-generic #30-Ubuntu SMP Mon Apr 20 16:58:30 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by weili-jiang** [comment]
I am not entirely sure how to reproduce this. Simply restarting the service via `systemctl` seems to have made it work again.

I write Python 3 and `systemd` unit files extensively at work so I'm willing to try and create a patch. Do you think this condition constitutes a `TemporaryCheckError`? I'm leaning towards yes, because restarting the service without any other changes to the system seems to have resolved it.

**Comment by languitar** [comment]
This looks like an uncovered corner case. I suspect you logged out of your session while autosuspend was running and the list of sessions obtained before wasn't valid anymore when trying to get session details.

Raising a `TemporaryCheckError` sounds like the right thing to do here. Would be great, if you could provide a patch!
